UniWatch/ViewModels/EnrollViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UniWatch.Models;

namespace UniWatch.ViewModels
{
    public class EnrollViewModel
    {
 
        public Class Class { get; set; }
        public List<StudentFound> StudentsFound { get; set; }

        //Default Constructor for EnrollViewModel
        public EnrollViewModel()
        {
            StudentsFound = new List<StudentFound>();
        }
    }

    public class StudentFound
    {
        public Student Student;
        public bool Enrolled;
    }
}

UniWatch/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniWatch.DataAccess;
using UniWatch.Models;

namespace UniWatch.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class ClassController : Controller
    {
        private IDataAccess _dataAccess;

        public ClassController() : this(new DataAccess.DataAccess())
        {
        }

        public ClassController(IDataAccess dataAccess)
        {
            _dataAccess = dataAccess;
        }

        //GET: Index
        /// <summary>
        /// Displays all classes taught by the teacher
        /// </summary>
        [OverrideAuthorization]
        [Authorize(Roles = "Teacher, Student")]
        public ActionResult Index()
        {
            // TODO: modify view to show appropriate information for either user type
            var user = _dataAccess.UserManager.GetUser();
            if(user is Teacher)
            {
                Teacher teacher = user as Teacher;
                return View("TeacherIndex", _dataAccess.ClassManager.GetClassesForTeacher(teacher.Id));
            }

            if (user is Student)
            {
                Student student = user as Student;
                return View("StudentIndex", _dataAccess.ClassManager.GetClassesForStudent(student.Id));
            }


            return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
        }

        // GET: Create
        /// <summary>
        /// Returns the view to create a new class
        /// </summary>
        public ActionResult Create()
        {
            return View();
        }

        //POST: Create
        /// <summary>
        /// Create class for the teacher
        /// </summary>
        /// <param name="class">Model containing information to create the class</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Number,Section,Semester,Year")] Class @class)
        {
            if(!ModelState.IsValid)
            {
                return View(@class);
            }
            try
            {
                var teacher = _dataAccess.UserManager.GetUser() as Teacher;
                var created = _dataAccess.ClassManager.CreateClass(@class.Name, @class.Number, @class.Section, @class.Semester, @class.Year, teacher.Id);
                return RedirectToAction("Index");
            }
            catch(InvalidOperationException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Conflict);
            }
        }

        //GET: Delete
        /// <summary>
        /// Sends user to the delete class page
        /// </summary>
        /// <param name="classId">Id of the class</param>
        public ActionResult Delete(int classId)
        {
            var @class = _dataAccess.ClassManager.GetById(classId);
            if(@class == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(@class);
        }

        //POST: Delete
        /// <summary>
        /// Deletes the class
        /// </summary>
        /// <param name="classId"></param>
        /// <returns></returns>
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int classId)
        {
            var @class = _dataAccess.ClassManager.GetById(classId);
            if(@class == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var teacherId = @class.Teacher.Id;

            _dataAccess.ClassManager.DeleteClass(classId);
            return RedirectToAction("Index", new { teacherId = teacherId });
        }

        protected override void Dispose(bool dispose)
        {
            _dataAccess.Dispose();
        }
    }
}

UniWatch/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniWatch.DataAccess;
using UniWatch.Models;
using UniWatch.ViewModels;

namespace UniWatch.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class StudentController : Controller
    {
        private IDataAccess _dataAccess;

        public StudentController() : this(new DataAccess.DataAccess())
        { }

        public StudentController(IDataAccess dataAccess)
        {
            _dataAccess = dataAccess;
        }

        // GET: /Student/Index?classId=1
        /// <summary>
        /// Display a list of students in a class
        /// </summary>
        /// <param name="classId">The id of the class</param>
        [HttpGet]
        public ActionResult Index(int classId)
        {
            var @class = _dataAccess.ClassManager.GetById(classId);
            if(@class == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var students = _dataAccess.ClassManager.GetEnrolledStudents(classId);
            return View(new ViewModels.EnrollIndexViewModel
            {
                Class = @class,
                EnrolledStudents = students
            });
        }

        /// <summary>
        /// Returns the view to enroll a student in a class. 
        /// </summary>
        /// <param name="classId">The id of the class</param>
        [HttpGet]
        public ActionResult Enroll(int classId)
        {
            var @class = _dataAccess.ClassManager.GetById(classId);
            if(@class == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            EnrollStudentViewModel viewModel = new EnrollStudentViewModel
            {
                Class = @class,
                StudentsFound = null
            };

            return View(viewModel);
        }

        /// <summary>
        /// Returns the view to enroll a student in a class. Searches for students
        /// that match the given id
        /// </summary>
        /// <param name="classId">The id of the class</param>
        /// <param name="searchTerm">The student search parameter</param>
        [HttpPost]
        public ActionResult Search(int classId, string searchTerm)
        {
            var @class = _dataAccess.ClassManager.GetById(classId);
            if(@class == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var found = _dataAccess.UserManager.SearchStudent(searchTerm);
            var enrolled = _dataAccess.ClassManager.GetEnrolledStudents(classId);

            // Set of student ids (for enrolled students)
            HashSet<int> enrolledSet = new HashSet<int>();
            foreach(var student in enrolled)
                enrolledSet.Add(student.Id);

            EnrollStudentViewModel viewModel = new EnrollStudentViewModel
            {
                Class = @class
            };

            foreach(Student student in found)
            {
                viewModel.StudentsFound.Add(new StudentFound
                {
                    Student = student,
                    Enrolled = enrolledSet.Contains(student.Id)
                });
            }

            return View("Enroll", viewModel);
        }

        // POST: /Student/Enroll?classId=1&studentId=1
        /// <summary>
        /// Enrolls a student into a class
        /// </summary>
        /// <param name="classId">The id of the class</param>
        /// <param name="studentId">The id of the student to enroll</param>
        [HttpPost]
        [ActionName("Enroll")]
        [ValidateAntiForgeryToken]
        public ActionResult EnrollConfirmed(int classId, int studentId)
        {
            var @class = _dataAccess.ClassManager.GetById(classId);
            var student = _dataAccess.UserManager.GetStudentById(studentId);
            if(@class == null || student == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                _dataAccess.ClassManager.EnrollStudent(classId, studentId);
            }
            catch(InvalidOperationException)
            {
                // Student is already enrolled in that class.
                return new HttpStatusCodeResult(HttpStatusCode.Conflict);
            }

            return RedirectToAction("Index", new { classId = classId });
        }

        // GET: /Student/Unenroll?classId=1&studentId=1
        /// <summary>
        /// Returns the view to unenroll a student from a class 
        /// </summary>
        /// <param name="classId">The id of the class</param>
        /// <param name="studentId">The id of the student</param>
        [HttpGet]
        public ActionResult UnEnroll(int classId, int studentId)
        {
            var @class = _dataAccess.ClassManager.GetById(classId);
            var student = _dataAccess.UserManager.GetStudentById(studentId);

            if(@class == null || student == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(new UnEnrollViewModel() { Class = @class, Student = student });
        }

        // POST: Unenroll
        /// <summary>
        /// Unenrolls a student from a class
        /// </summary>
        /// <param name="classId">The id of the class</param>
        /// <param name="studentId">The id of the student to enroll</param>
        [HttpPost]
        [ActionName("UnEnroll")]
        [ValidateAntiForgeryToken]
        public ActionResult UnEnrollCofirmed(int classId, int studentId)
        {
            var @class = _dataAccess.ClassManager.GetById(classId);
            var student = _dataAccess.UserManager.GetStudentById(studentId);
            if(@class == null || student == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                _dataAccess.ClassManager.UnEnrollStudent(classId, studentId);
            }
            catch(InvalidOperationException)
            {
                // Student is not enrolled in that class.
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return RedirectToAction("Index", new { classId = classId });
        }

        /// <summary>
        /// Returns the view to search for a student (for uploading profile images)
        /// </summary>
        /// <param name="searchTerm">The parameter used to search for a student</param>
        [HttpGet]
        [ActionName("Profile")]
        public ActionResult StudentProfile(string searchTerm)
        {
            var students = _dataAccess.UserManager.SearchStudent(searchTerm);

            if(Request.IsAjaxRequest())
            {
                return PartialView("_ProfileSearch", students);
            }

            return View(students);
        }

        /// <summary>
        /// Displays a page to upload images of the student's face
        /// </summary>
        /// <param name="studentId">The id of the student</param>
        [HttpGet]
        public ActionResult Upload(int studentId)
        {
            var student = _dataAccess.UserManager.GetStudentById(studentId);
            if(student == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(student);
        }

        /// <summary>
        /// Upload images of the student's face
        /// </summary>
        /// <param name="studentId">The id of the student</param>
        /// <param name="files">The images to upload</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(int studentId, IEnumerable<HttpPostedFileBase> files)
        {
            var student = _dataAccess.UserManager.GetStudentById(studentId);
            if(student == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if(!files.Any() || (files.Count() == 1 && files.ElementAt(0) == null))
            {
                ViewBag.ErrorMessage = "No file selected";
                return View(student);
            }

            var validImageTypes = new string[]
            {
                "image/gif",
                "image/jpeg",
                "image/pjpeg",
                "image/png",
                "image/bmp"
            };

            var images = new List<Stream>(files.Count());
            foreach(var file in files)
            {
                // TODO: Determine upload limit
                if(file.ContentLength <= 0 /*|| file.ContentLength >= MAX_SIZE*/)
                {
                    ViewBag.ErrorMessage = "File must not be empty and must not exceed MAX_SIZE";
                    return View(student);
                }
                else if(!validImageTypes.Contains(file.ContentType))
                {
                    ViewBag.ErrorMessage = "File type must be either gif, jpeg or png";
                    return View(student);
                }

                images.Add(file.InputStream);
            }

            _dataAccess.UserManager.SetStudentProfile(student.Id, images);
            return RedirectToAction("Upload", new { studentId = student.Id });
        }
    }
}

UniWatch/Views/Student/Enroll.cshtml
@model UniWatch.ViewModels.EnrollStudentViewModel

<h3>Enroll a Student</h3>
<hr />

<p>
    @Html.ActionLink("Back", "Index", new { classId = Model.Class.Id }, new { @class = "btn btn-default" })
</p>

<div class="row">
    <div class="form-group col-md-3">
        @using(Html.BeginForm("Search", "Student", new { classId = Model.Class.Id }, FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="input-group">
                <input id="searchTerm" name="searchTerm" type="text" class="form-control" maxlength="64" placeholder="Search" />
                <div class="input-group-btn">
                    <input type="submit" class="btn btn-default" value="Search" />
                </div>
            </div>
        }
    </div>
</div>


@if(Model.StudentsFound == null)
{
    <p>Search for the student by Id</p>
}
else if(!Model.StudentsFound.Any())
{
    <p>No results to display</p>
}
else
{
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach(var student in Model.StudentsFound)
            {
                <tr>
                    <td>@student.Student.Id</td>
                    <td>@student.Student.FirstName</td>
                    <td>@student.Student.LastName</td>
                    <td>
                        @if(student.Enrolled)
                        {
                            @:Already enrolled
                        }
                        else
                        {
                            using(Html.BeginForm("Enroll", "Student", new { classId = Model.Class.Id, studentId = student.Student.Id }, FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <input type="submit" value="Enroll" class="btn btn-success" />
                            }
                        }
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>

    <p>
        @Html.ActionLink("Back", "Index", new { classId = Model.Class.Id }, new { @class = "btn btn-default" })
    </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UniWatch/Views/Student/Index.cshtml
@model UniWatch.ViewModels.EnrollIndexViewModel

<h3>Students in @Model.Class.Name</h3>
<hr />

<p>
    @Html.ActionLink("Back", "Index", "Lecture", new { classId = Model.Class.Id }, new { @class = "btn btn-default" })
    @Html.ActionLink("Enroll a Student", "Enroll", "Student", new {classId = Model.Class.Id}, new {@class = "btn btn-primary"})
</p>

@if (!Model.EnrolledStudents.Any())
{
    <p>No students currently enrolled in this class.</p>
}
else {
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="table-inverse">
            <tr>
                <th>Name</th>
                <th></th>
            </tr>
            </thead>

            <tbody>
            @foreach (var student in Model.EnrolledStudents)
            {
                <tr>
                    <td class="student-name">
                        @Html.ActionLink($"{student.FirstName} {@student.LastName}", "Upload", "Student", new { classId = Model.Class.Id, studentId = student.Id }, null)
                    </td>
                    <td>
                        @Html.ActionLink("UnEnroll", "UnEnroll", "Student", new { classId = Model.Class.Id, studentId = student.Id }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>

    <p>
        @Html.ActionLink("Back", "Index", "Lecture", new { classId = Model.Class.Id }, new { @class = "btn btn-default" })
        @Html.ActionLink("Enroll a Student", "Enroll", "Student", new { classId = Model.Class.Id }, new { @class = "btn btn-primary" })
    </p>
}

UniWatch/Views/Student/Profile.cshtml
@model IEnumerable<UniWatch.Models.Student>

<h3></h3>
<br/>

<p>@Html.ActionLink("Back", "Index", "Class", null, new { @class = "btn btn-default" })</p>

<div class="row help-block">
    &nbsp;
    <div class="col-md-4">
        <div class="form-group form-horizontal">
            @using (Ajax.BeginForm(
                new AjaxOptions
                {
                    HttpMethod = "get",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "studentList"
                }))
            {
                <div class="input-group">
                    <input type="search" name="searchTerm" class="form-control"/>
                    <div class="input-group-btn">
                        <input type="submit" class="btn btn-default" value="Search"/>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@Html.Partial("_ProfileSearch", Model)

UniWatch/Views/Student/UnEnroll.cshtml
@model UniWatch.ViewModels.UnEnrollViewModel

<h3>Unenroll @($"{Model.Student.FirstName} {Model.Student.LastName}") from @Model.Class.Name?</h3>

<p>Removing this student from this class will delete all associated data and cannot be undone. Proceed?</p>

<div>
    @using (Html.BeginForm("UnEnroll", "Student", new { classId = Model.Class.Id, studentId = Model.Student.Id }, FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Cancel", "Index", new { classId = Model.Class.Id }, new { @class = "btn btn-default" })
            <input type="submit" value="Confirm" class="btn btn-danger" />
        </div>
    }
</div>

UniWatch/Views/Student/Upload.cshtml
@model UniWatch.Models.Student
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if(Model.Profile.Images.Any())
{
    <h3>Facial Profile for @string.Format($"{Model.FirstName} {Model.LastName}")</h3>
    <hr/>

    <div class="row">
        @for(int i = 0; i < Model.Profile.Images.Count; i++)
        {
            var image = Model.Profile.Images.ElementAt(i);
            <div class="col-md-4">
                <div class="thumbnail">
                    <a href="@image.Url" alt="Profile image 1">
                        <img src="@image.Url" class="img-responsive" alt="Profile image 1" />
                        <div class="caption">
                            Profile image @(i + 1)
                        </div>
                    </a>
                </div>
            </div>
        }
    </div>
}
else
{
    <h3>@string.Format($"{Model.FirstName} {Model.LastName}") - Upload images of student's face</h3>
    <hr />

    <div class="row">
        <div class="navbar-form">
            <div class="form-group">
                @using(Html.BeginForm("Upload", "Student", new { studentId = Model.Id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="input-group">
                        <input type="file" multiple name="files" accept="image/jpeg, image/png, image/gif, image/bmp" class="form-control" />
                        <div class="input-group-btn">
                            <input type="submit" value="Upload" class="btn btn-default" />
                        </div>
                    </div>
                    <p class="text-danger">@ViewBag.ErrorMessage</p>
                }
            </div>
        </div>
    </div>
}

UniWatch/Views/Student/_ProfileSearch.cshtml
@model IEnumerable<UniWatch.Models.Student>

<div id="studentList" class="row">
    <div class="col-md-4">
        @if(!Model.Any())
        {
            <p>No results to display</p>
        }
        else
        {
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Student</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach(var student in Model)
                    {
                        <tr>
                            <td>
                                @Html.ActionLink($"{student.FirstName} {student.LastName}", "Upload", new { studentId = student.Id })
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>

            <p>@Html.ActionLink("Back", "Index", "Class", null, new { @class = "btn btn-default" })</p>
        }
    </div>
</div>